site_name: Laraval Extended Validation
site_description: Documentation for Laraval Extended Validation

repo_name: sandervankasteel/laravel-extended-validation
repo_url: https://github.com/sandervankasteel/laravel-extended-validation
edit_uri: https://github.com/sandervankasteel/laravel-extended-validation/edit/main/docs/

theme:
  name: material
  font:
    text: 'Nunito'
    code: 'Fira Code'
  palette:
    scheme: preference
    primary: blue
    accent: blue
#  favicon: images/favicon.ico
#  logo: images/logo.svg
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.instant

extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sandervankasteel/laravel-extended-validation
      name: Laraval Extended Validation repository

plugins:
  - search: { }

nav:
  - index.md
  - 'General':
      - general/OrRule.md
  - 'Barcode':
      - barcode/EAN5.md
      - barcode/EAN8.md
      - barcode/EAN13.md
      - barcode/ISBN10.md
      - barcode/ISBN13.md
      - barcode/UPC-A.md
  - 'Color':
      - color/HexColor.md
  - 'Database':
      - database/LessThanValue.md
      - database/LessThanOrEqualValue.md
      - database/MoreThanValue.md
      - database/MoreThanOrEqualValue.md
      - database/MustBeEqualValue.md
  - 'Date and time':
      - dateandtime/Time12Hour.md
      - dateandtime/Time24Hour.md
      - dateandtime/UnixTime.md
  - 'Locales':
      - 'BE':
          - locale/BE/Address/PostalCode.md
          - locale/BE/Company/VatNumber.md
      - 'DE':
          - locale/DE/Company/VatNumber.md
          - locale/DE/Address/PostalCode.md
      - 'FR':
          - locale/FR/Company/VatNumber.md
          - locale/FR/Address/PostalCode.md
      - 'LU':
          - locale/LU/Company/VatNumber.md
      - 'NL':
          - locale/NL/Address/PostalCode.md
          - locale/NL/Person/SocialSecurityNumber.md
          - locale/NL/Company/VatNumber.md
      - 'UK':
          - locale/UK/Address/PostalCode.md
  - 'Network':
      - network/IPv4.md
      - network/IPv6.md
      - network/MacAddress.md
  - 'Payment':
      - payment/AmericanExpress.md
      - payment/IBAN.md
      - payment/MasterCard.md
      - payment/Visa.md

markdown_extensions:
  - admonition: { }
  - meta: { }
  - toc:
      permalink: '#'
  - pymdownx.details: { }
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.superfences: { }
  - pymdownx.keys: { }

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.4.0/highlight.min.js
  - javascripts/highlight.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.4.0/styles/atom-one-dark-reasonable.min.css