site_name: Laraval Extended Validation
site_description: Documentation for Laraval Extended Validation
site_author: Sander van Kasteel

repo_name: sandervankasteel/laravel-extended-validation
repo_url: https://github.com/sandervankasteel/laravel-extended-validation
edit_uri: https://github.com/sandervankasteel/laravel-extended-validation/edit/main/docs/

strict: true

theme:
  name: material
  font:
    text: 'Nunito'
    code: 'Fira Code'
  palette:
    scheme: preference
    primary: blue
    accent: blue
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.instant

extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sandervankasteel/laravel-extended-validation
      name: Laraval Extended Validation repository

plugins:
  - search: { }

nav:
  - index.md
  - 'General':
      - general/OrRule.md
  - 'Barcode':
      - barcode/ASIN.md
      - barcode/EAN5.md
      - barcode/EAN8.md
      - barcode/EAN13.md
      - barcode/ISBN10.md
      - barcode/ISBN13.md
      - barcode/ISMN.md
      - barcode/JAN.md
      - barcode/UPC-A.md
      - barcode/UPC-E.md
  - 'Color':
      - color/HexColor.md
      - color/RGB.md
      - color/RGBA.md
  - 'Database':
      - database/LessThanValue.md
      - database/LessThanOrEqualValue.md
      - database/MoreThanValue.md
      - database/MoreThanOrEqualValue.md
      - database/MustBeEqualValue.md
  - 'Date and time':
      - dateandtime/Time12Hour.md
      - dateandtime/Time24Hour.md
      - dateandtime/TimeZoneAbbr.md
      - dateandtime/UnixTime.md
  - 'Locales':
      - 'Belgium (BE)':
          - locale/BE/Address/PostalCode.md
          - locale/BE/Company/VatNumber.md
      - 'Germany (DE)':
          - locale/DE/Company/VatNumber.md
          - locale/DE/Address/PostalCode.md
      - 'France (FR)':
          - locale/FR/Company/VatNumber.md
          - locale/FR/Address/PostalCode.md
      - 'Ireland (IE)':
          - locale/IE/Address/PostalCode.md
      - 'Italy (IT)':
          - locale/IT/Address/PostalCode.md
          - locale/IT/Company/VatNumber.md
      - 'Luxemburg (LU)':
          - locale/LU/Company/VatNumber.md
          - locale/LU/Address/PostalCode.md
      - 'Netherlands, The (NL)':
          - locale/NL/Address/PostalCode.md
          - locale/NL/Person/SocialSecurityNumber.md
          - locale/NL/Company/VatNumber.md
      - 'Portugal (PT)':
          - locale/PT/Address/PostalCode.md
      - 'Spain (ES)':
          - locale/ES/Address/PostalCode.md
          - locale/ES/Company/VatNumber.md
      - 'South Korea (KR)':
          - locale/SK/Address/PostalCode.md
      - 'United Kingdom (UK)':
          - locale/UK/Address/PostalCode.md
  - 'Network':
      - network/Domain.md
      - network/IPv4.md
      - network/IPv6.md
      - network/MacAddress.md
  - 'Payment':
      - payment/AmericanExpress.md
      - payment/DiscoverCard.md
      - payment/IBAN.md
      - payment/MasterCard.md
      - payment/Visa.md

markdown_extensions:
  - admonition: { }
  - meta: { }
  - toc:
      permalink: '#'
  - pymdownx.details: { }
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.superfences: { }
  - pymdownx.keys: { }

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.4.0/highlight.min.js
  - javascripts/highlight.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.4.0/styles/atom-one-dark-reasonable.min.css
