name: Check code style

on: [push]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga:3.13.0
        with:
          args: --config=.php-cs-fixer.php --allow-risky=yes --dry-run
